server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: requestTask
          uri: http://localhost:8081
          predicates:
            - Path=/requestTasks/** 
        - id: processTask
          uri: http://localhost:8082
          predicates:
            - Path=/processTasks/** 
        - id: myPage
          uri: http://localhost:8083
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: requestTask
          uri: http://user11-requestTask:8080
          predicates:
            - Path=/requestTasks/** 
        - id: processTask
          uri: http://user11-processTask:8080
          predicates:
            - Path=/processTasks/** 
        - id: myPage
          uri: http://user11-myPage:8080
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8088